### ISSUE TITLE
Serial Protocol undocumented and probably insecure?

### ISSUE THREAD

**Issue by vogt31337** [jareklupinski/zamek#3]
Hi,

just browsing through this repo and I like the project so far. But I don't find any docu on the serial protocol used: I just figured out sending a 'd' to the device, will dump the whole eeprom store.
I hope this is just for debugging, and Can be removed...

BR

**Comment by jareklupinski** [comment]
Hi vogt, the intention for this is to allow a PC app attached to the Zamek's Serial Port to download the encrypted payload from the device for ease-of-use tasks like credential entry and backups. As only the encrypted blob can be downloaded, the PC still needs whichever key you put into the device to decrypt the contents. This will ( in the future ) be something the user has to toggle, something like a dialog will pop up on the device requesting the user to confirm their blob is about to be dumped before it actually connects and dumps.

-d for dump :)
