### ISSUE TITLE
BOM and layout missing

### ISSUE THREAD

**Issue by Tobiassss** [jareklupinski/zamek#5]
Hi,

first: very nice project, thank you very much for all the effort you put into it!

I saw it and immediately want to build one by myself...
...BUT:
Why is there no complete BOM?
I mean you can takes some guesses and with some experience you'll find the parts. But especially for the Trackball, LiPo and OLED a little more information would be very convenient.

Why is the PCB not routed?
It seems that the Autorouter produces a functional design within a few seconds. But still, why not just share your proven design?

**Comment by jareklupinski** [comment]
Unfortunately the proven design proved to be faulty :( the finished PCB needed three bodge wires to actually work, and I quickly began working on a completely different USB-C version to replace it.

I'm dragging my feet a bit with the firmware, but I'll post the USB-C board with the corrected traces soon :)

**Comment by ryuk171** [comment]
i am new to all this it says nets missing , help!!

**Comment by jareklupinski** [comment]
Hello! Thank you all for keeping on me about this :) I have uploaded the latest USBC variant that I am working on; unfortunately the older USB-A variant was impossible to produce cheaply while being waterproof.

The new version uses only two buttons and two hall effects sensors to read inputs from external rotary switches! https://github.com/jareklupinski/zamek/tree/master/brd%2Bsch 

Working on the code now, PRs welcome and Stay tuned ;)
